on: 
  push:
    branches: 
      - '*'
      - '!master'
      - '!beta'

name: CI/CD
jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Dotnet Build
      run: dotnet build -c Release
